//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SmsConsoleService.NAVWEBREF {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SURESMSSERVICE_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/SURESMSSERVICE")]
    public partial class SURESMSSERVICE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBulKSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateConfirmSentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SURESMSSERVICE() {
            this.Url = global::SmsConsoleService.Properties.Settings.Default.SmsConsoleService_NAVWEBREF_SURESMSSERVICE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBulKSMSCompletedEventHandler GetBulKSMSCompleted;
        
        /// <remarks/>
        public event UpdateConfirmSentCompletedEventHandler UpdateConfirmSentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/SURESMSSERVICE:GetBulKSMS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/SURESMSSERVICE", ResponseElementName="GetBulKSMS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/SURESMSSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetBulKSMS() {
            object[] results = this.Invoke("GetBulKSMS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBulKSMSAsync() {
            this.GetBulKSMSAsync(null);
        }
        
        /// <remarks/>
        public void GetBulKSMSAsync(object userState) {
            if ((this.GetBulKSMSOperationCompleted == null)) {
                this.GetBulKSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBulKSMSOperationCompleted);
            }
            this.InvokeAsync("GetBulKSMS", new object[0], this.GetBulKSMSOperationCompleted, userState);
        }
        
        private void OnGetBulKSMSOperationCompleted(object arg) {
            if ((this.GetBulKSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBulKSMSCompleted(this, new GetBulKSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/SURESMSSERVICE:UpdateConfirmSent", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/SURESMSSERVICE", ResponseElementName="UpdateConfirmSent_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/SURESMSSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool UpdateConfirmSent(int entryNo) {
            object[] results = this.Invoke("UpdateConfirmSent", new object[] {
                        entryNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateConfirmSentAsync(int entryNo) {
            this.UpdateConfirmSentAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void UpdateConfirmSentAsync(int entryNo, object userState) {
            if ((this.UpdateConfirmSentOperationCompleted == null)) {
                this.UpdateConfirmSentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateConfirmSentOperationCompleted);
            }
            this.InvokeAsync("UpdateConfirmSent", new object[] {
                        entryNo}, this.UpdateConfirmSentOperationCompleted, userState);
        }
        
        private void OnUpdateConfirmSentOperationCompleted(object arg) {
            if ((this.UpdateConfirmSentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateConfirmSentCompleted(this, new UpdateConfirmSentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetBulKSMSCompletedEventHandler(object sender, GetBulKSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBulKSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBulKSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateConfirmSentCompletedEventHandler(object sender, UpdateConfirmSentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateConfirmSentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateConfirmSentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591